/**
 * AVORA AI Operational Intelligence
 * Gemini-powered insights for hospital operations.
 * All outputs are clearly marked as AI-generated and require human review.
 */
import { HospitalState, AvoraInsight, InsightCategory, InsightUrgency, DepartmentLoad } from '../types/index.js';

const AI_DISCLAIMER = 'This insight is AI-generated by AVORA and requires human review before action. Do not make clinical or operational decisions based solely on this insight.';

function makeInsight(
  organizationId: string,
  id: string,
  category: InsightCategory,
  urgency: InsightUrgency,
  title: string,
  summary: string,
  detail?: string,
  recommendation?: string,
  affectedDepartment?: string,
  confidence: AvoraInsight['confidence'] = 'MEDIUM'
): AvoraInsight {
  const now = new Date().toISOString();
  return {
    id, organizationId, category, urgency, title, summary, detail, recommendation,
    affectedDepartment, confidence, generatedAt: now,
    expiresAt: new Date(Date.now() + 3600000).toISOString(),
    isAcknowledged: false, isActedUpon: false,
    aiModelUsed: 'AVORA-Insight-Engine-v1',
    disclaimer: AI_DISCLAIMER,
  };
}

export function analyzeHospitalState(state: HospitalState): AvoraInsight[] {
  const insights: AvoraInsight[] = [];
  const orgId = state.organizationId;

  // Bottleneck detection
  const criticalDepts = state.departments.filter(d => d.alertLevel === 'CRITICAL');
  criticalDepts.forEach((dept, i) => {
    insights.push(makeInsight(
      orgId, `insight-bottleneck-${dept.departmentId}`,
      'BOTTLENECK', 'ACTION_REQUIRED',
      `Critical Bottleneck: ${dept.departmentName}`,
      `${dept.departmentName} has ${dept.patientsWaiting} patients waiting with avg ${dept.averageWaitMinutes} min wait at ${dept.capacityPercentage}% capacity.`,
      `${dept.overdueTasks} tasks are overdue. Longest wait: ${dept.longestWaitMinutes} min.`,
      'Consider immediate resource reallocation or activating overflow protocol.',
      dept.departmentName, 'HIGH'
    ));
  });

  // Resource optimization
  if (state.resources.nursesAvailable < 3 && state.resources.nursesOnDuty > 8) {
    insights.push(makeInsight(
      orgId, 'insight-nurse-load', 'RESOURCE_OPTIMIZATION', 'RECOMMENDATION',
      'Nurse Workload Imbalance Detected',
      `${state.resources.nursesOnDuty - state.resources.nursesAvailable} of ${state.resources.nursesOnDuty} nurses are currently occupied.`,
      'This may indicate uneven task distribution across nursing staff.',
      'Review nurse task assignments and redistribute if overloaded nurses exist.',
      undefined, 'MEDIUM'
    ));
  }

  // Lab capacity
  if (state.resources.labCapacityPercentage > 80) {
    insights.push(makeInsight(
      orgId, 'insight-lab-capacity', 'DEPARTMENT_LOAD', 'ACTION_REQUIRED',
      `Lab at ${state.resources.labCapacityPercentage}% Capacity`,
      `Laboratory is near capacity. New urgent orders may face processing delays.`,
      'Consider activating secondary processing stations or routing non-urgent samples to the afternoon shift.',
      'Notify lab supervisor and consider prioritizing STAT orders.',
      'Laboratory', 'HIGH'
    ));
  }

  // Bed availability
  if (state.resources.bedsAvailable < 10) {
    const pct = Math.round((state.resources.bedsOccupied / state.resources.bedsTotal) * 100);
    insights.push(makeInsight(
      orgId, 'insight-bed-shortage', 'RESOURCE_OPTIMIZATION', 'URGENT',
      `Low Bed Availability — ${state.resources.bedsAvailable} Beds Available`,
      `Hospital is at ${pct}% bed occupancy with only ${state.resources.bedsAvailable} beds available.`,
      `${state.resources.emergencyBedsAvailable} emergency beds remain available.`,
      'Review patients eligible for early discharge. Alert ward supervisors.',
      undefined, 'HIGH'
    ));
  }

  // Task overdue ratio
  const overdueRatio = state.totalTasksActive > 0 ? state.totalTasksOverdue / state.totalTasksActive : 0;
  if (overdueRatio > 0.15) {
    insights.push(makeInsight(
      orgId, 'insight-overdue-tasks', 'BOTTLENECK', 'ACTION_REQUIRED',
      `${state.totalTasksOverdue} Overdue Tasks Across Hospital`,
      `${(overdueRatio * 100).toFixed(0)}% of active tasks are overdue. This may impact patient flow.`,
      `${state.totalTasksEscalated} tasks have been escalated. Task completion rate last hour: ${state.taskCompletionRateLastHour}%.`,
      'Review escalated tasks and reassign overdue tasks to available staff.',
      undefined, 'HIGH'
    ));
  }

  // Pharmacy queue
  if (state.resources.pharmacyQueueDepth > 25) {
    insights.push(makeInsight(
      orgId, 'insight-pharmacy-queue', 'DEPARTMENT_LOAD', 'RECOMMENDATION',
      `High Pharmacy Queue — ${state.resources.pharmacyQueueDepth} Pending`,
      `Pharmacy has ${state.resources.pharmacyQueueDepth} pending dispense orders.`,
      'Patients may experience delays in receiving medications after discharge.',
      'Consider calling in additional pharmacy staff or activating pre-packing for common medications.',
      'Pharmacy', 'MEDIUM'
    ));
  }

  return insights;
}

export function generateMockInsights(organizationId: string, state: HospitalState): AvoraInsight[] {
  const baseInsights = analyzeHospitalState(state);
  const extraInsights: AvoraInsight[] = [
    makeInsight(
      organizationId, 'insight-morning-peak', 'SHIFT_PLANNING', 'INFORMATIONAL',
      'Morning OPD Peak Predicted',
      'Based on historical patterns, OPD load typically peaks between 10AM–12PM. Current trajectory is consistent with this pattern.',
      'Cardiology and General Medicine OPDs usually see 40% of daily patients in this window.',
      'Ensure full doctor complement is available from 10AM. Pre-stage nursing resources.',
      undefined, 'HIGH'
    ),
    makeInsight(
      organizationId, 'insight-inventory', 'INVENTORY_FORECAST', 'RECOMMENDATION',
      'Paracetamol 500mg Stock Approaching Reorder Level',
      'Based on current prescription velocity, Paracetamol 500mg will reach minimum stock level in approximately 3 days.',
      'Current stock: 847 units. Average daily consumption: 280 units. Reorder level: 200 units.',
      'Initiate purchase order for Paracetamol 500mg. Estimated requirement: 2,000 units for 7-day buffer.',
      'Pharmacy', 'MEDIUM'
    ),
  ];
  return [...baseInsights, ...extraInsights];
}
