import React, { useState } from "react";
import { Zap, CheckCircle2, ArrowRight, TrendingUp, Package, Clock, Users, AlertTriangle, Info } from "lucide-react";
import { AvoraInsight, InsightCategory, InsightUrgency } from "../../types/index.js";

interface Props { insights: AvoraInsight[]; }

const URGENCY_CONFIG: Record<InsightUrgency,{color:string;bg:string;label:string;icon:any}> = {
  INFORMATIONAL: { color:"#64748b",bg:"rgba(100,116,139,0.1)",label:"Info",     icon:Info },
  RECOMMENDATION:{ color:"#0ea5e9",bg:"rgba(14,165,233,0.1)", label:"Insight",  icon:TrendingUp },
  ACTION_REQUIRED:{ color:"#f97316",bg:"rgba(249,115,22,0.1)",label:"Action",   icon:AlertTriangle },
  URGENT:        { color:"#ef4444",bg:"rgba(239,68,68,0.1)",  label:"Urgent",   icon:Zap },
};

const CATEGORY_ICONS: Record<InsightCategory, any> = {
  DEPARTMENT_LOAD:       TrendingUp,
  BOTTLENECK:            AlertTriangle,
  RESOURCE_OPTIMIZATION: Users,
  INVENTORY_FORECAST:    Package,
  PATIENT_JOURNEY:       ArrowRight,
  SHIFT_PLANNING:        Clock,
  EMERGENCY_PREDICTION:  Zap,
};

export const AvoraInsightPanel: React.FC<Props> = ({ insights }) => {
  const [acknowledged, setAcknowledged] = useState<Set<string>>(new Set());
  const [expanded, setExpanded] = useState<string | null>(null);

  const visible = insights.filter(i => !acknowledged.has(i.id));

  return (
    <div>
      <div style={{ display:"flex",alignItems:"center",gap:12,marginBottom:20 }}>
        <div style={{ display:"flex",alignItems:"center",gap:8 }}>
          <div style={{ width:28,height:28,background:"linear-gradient(135deg,#6366f1,#8b5cf6)",borderRadius:8,display:"flex",alignItems:"center",justifyContent:"center" }}>
            <Zap size={14}/>
          </div>
          <div>
            <h2 style={{ fontSize:16,fontWeight:700,margin:0 }}>AVORA AI Insights</h2>
            <p style={{ fontSize:10,color:"#64748b",margin:0 }}>All insights require human review before action</p>
          </div>
        </div>
        <span style={{ fontSize:11,background:"rgba(99,102,241,0.15)",color:"#818cf8",padding:"3px 10px",borderRadius:10,border:"1px solid rgba(99,102,241,0.2)" }}>
          {visible.length} Active
        </span>
      </div>

      {/* Disclaimer Banner */}
      <div style={{ background:"rgba(99,102,241,0.06)",border:"1px solid rgba(99,102,241,0.15)",borderRadius:10,padding:"10px 16px",marginBottom:20,display:"flex",alignItems:"center",gap:10 }}>
        <Zap size={14} style={{ color:"#818cf8",flexShrink:0 }} />
        <p style={{ fontSize:11,color:"#818cf8",margin:0 }}>
          <strong>⚡ AVORA AI Insight Engine</strong> — These insights are generated by AVORA&apos;s operational analysis algorithms. They require human review and should not be acted upon autonomously. Always apply clinical and operational judgment.
        </p>
      </div>

      <div style={{ display:"flex",flexDirection:"column",gap:12 }}>
        {visible.map(insight => {
          const urgConf = URGENCY_CONFIG[insight.urgency];
          const CatIcon = CATEGORY_ICONS[insight.category] ?? TrendingUp;
          const isExpanded = expanded === insight.id;
          return (
            <div key={insight.id} style={{ background:"rgba(255,255,255,0.02)",border:`1px solid ${urgConf.color}33`,borderLeft:`3px solid ${urgConf.color}`,borderRadius:12,padding:16,transition:"all 0.2s" }}>
              <div style={{ display:"flex",alignItems:"flex-start",gap:12 }}>
                <div style={{ width:36,height:36,borderRadius:8,background:urgConf.bg,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0 }}>
                  <CatIcon size={16} style={{ color:urgConf.color }} />
                </div>
                <div style={{ flex:1,minWidth:0 }}>
                  <div style={{ display:"flex",alignItems:"center",gap:8,marginBottom:4,flexWrap:"wrap" }}>
                    <span style={{ fontSize:10,padding:"2px 8px",borderRadius:8,background:urgConf.bg,color:urgConf.color,fontWeight:700,border:`1px solid ${urgConf.color}33` }}>
                      ⚡ AI · {urgConf.label}
                    </span>
                    {insight.affectedDepartment && (
                      <span style={{ fontSize:10,color:"#64748b",background:"rgba(255,255,255,0.05)",padding:"2px 8px",borderRadius:8 }}>
                        {insight.affectedDepartment}
                      </span>
                    )}
                    <span style={{ fontSize:10,color:"#475569",marginLeft:"auto" }}>
                      Confidence: <span style={{ color:insight.confidence==="HIGH"?"#22c55e":insight.confidence==="MEDIUM"?"#f59e0b":"#64748b" }}>{insight.confidence}</span>
                    </span>
                  </div>
                  <h3 style={{ fontSize:14,fontWeight:600,margin:"0 0 4px 0" }}>{insight.title}</h3>
                  <p style={{ fontSize:12,color:"#94a3b8",margin:0 }}>{insight.summary}</p>
                  {isExpanded && insight.detail && (
                    <div style={{ marginTop:12,padding:"10px 12px",background:"rgba(255,255,255,0.03)",borderRadius:8,border:"1px solid rgba(255,255,255,0.06)" }}>
                      <p style={{ fontSize:11,color:"#94a3b8",margin:"0 0 8px 0" }}>{insight.detail}</p>
                      {insight.recommendation && (
                        <div style={{ display:"flex",alignItems:"flex-start",gap:8 }}>
                          <ArrowRight size={12} style={{ color:"#22c55e",marginTop:2,flexShrink:0 }} />
                          <p style={{ fontSize:11,color:"#22c55e",margin:0 }}><strong>Recommendation:</strong> {insight.recommendation}</p>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              </div>
              <div style={{ display:"flex",gap:8,marginTop:12 }}>
                <button onClick={() => setExpanded(isExpanded ? null : insight.id)} style={{ background:"rgba(255,255,255,0.05)",border:"1px solid rgba(255,255,255,0.08)",color:"#94a3b8",borderRadius:7,padding:"5px 12px",cursor:"pointer",fontSize:11,flex:1 }}>
                  {isExpanded ? "Collapse" : "View Detail"}
                </button>
                <button onClick={() => setAcknowledged(prev => new Set([...prev, insight.id]))} style={{ background:"rgba(34,197,94,0.1)",border:"1px solid rgba(34,197,94,0.2)",color:"#22c55e",borderRadius:7,padding:"5px 12px",cursor:"pointer",fontSize:11,display:"flex",alignItems:"center",gap:5 }}>
                  <CheckCircle2 size={11}/> Acknowledge
                </button>
              </div>
            </div>
          );
        })}
        {visible.length === 0 && (
          <div style={{ textAlign:"center",padding:60,color:"#334155" }}>
            <CheckCircle2 size={40} style={{ color:"#22c55e",marginBottom:12 }} />
            <p style={{ fontSize:14,color:"#64748b" }}>All insights acknowledged. AVORA is monitoring for new patterns.</p>
          </div>
        )}
      </div>
    </div>
  );
};
